/**
 * Robots.txt Configuration for Production
 * Controls search engine crawler access
 * 
 * SEO: Guides crawlers on what to index and what to avoid
 * Location: /robots.txt (automatically generated by Next.js)
 * 
 * @see https://nextjs.org/docs/app/api-reference/file-conventions/metadata/robots
 */

import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://muslimeen.space';
  
  // Check if we're in production
  const isProduction = process.env.NODE_ENV === 'production';
  
  // Common disallowed paths (applies to all crawlers)
  const commonDisallowed = [
    // API routes - never index these
    '/api/',
    '/_next/',
    '/static/',
    
    // Authentication pages
    '/login',
    '/register',
    '/auth/',
    
    // Private/authenticated pages - require login
    '/dashboard',
    '/dashboard/',
    '/profile',
    '/profile/',
    '/messages',
    '/messages/',
    '/settings',
    '/settings/',
    '/verification',
    '/verification/',
    '/trust-score',
    '/trust-score/',
    '/invites',
    '/invites/',
    
    // Search and filter pages (prevent duplicate content indexing)
    '/search?',
    '/*?sort=',
    '/*?filter=',
    '/*?page=',
    
    // User-generated content that shouldn't be indexed
    '/admin/',
    '/mod/',
  ];

  // Block AI training crawlers (optional - these consume bandwidth)
  const aiCrawlers = [
    'GPTBot',           // OpenAI
    'ChatGPT-User',     // OpenAI
    'Claude-Web',       // Anthropic
    'ClaudeBot',        // Anthropic
    'CCBot',            // Common Crawl
    'PerplexityBot',    // Perplexity
    'anthropic-ai',     // Anthropic
    'Google-Extended',  // Google Bard/AI (optional)
  ];

  // Build rules array
  const rules: MetadataRoute.Robots['rules'] = [
    // Default rule for all crawlers
    {
      userAgent: '*',
      allow: isProduction ? ['/', '/about', '/islamic-finance', '/connections', '/marketplace/'] : [],
      disallow: isProduction ? commonDisallowed : ['/'],
    },
    
    // Googlebot-specific rules
    {
      userAgent: 'Googlebot',
      allow: isProduction ? ['/', '/about', '/islamic-finance', '/connections', '/marketplace/'] : [],
      disallow: isProduction ? commonDisallowed : ['/'],
    },
    
    // Googlebot-Image (allow images)
    {
      userAgent: 'Googlebot-Image',
      allow: ['/'],
    },
    
    // Bingbot-specific rules
    {
      userAgent: 'Bingbot',
      allow: isProduction ? ['/', '/about', '/islamic-finance', '/connections', '/marketplace/'] : [],
      disallow: isProduction ? commonDisallowed : ['/'],
    },
  ];

  // Add AI crawler blocks in production
  if (isProduction) {
    aiCrawlers.forEach((crawler) => {
      rules.push({
        userAgent: crawler,
        disallow: ['/'],
      });
    });
  }

  return {
    rules,
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
