/**
 * Sitemap Configuration for Production
 * Helps search engines discover and index pages
 * 
 * SEO: Essential for crawlability and indexation
 * Location: /sitemap.xml (automatically generated by Next.js)
 * 
 * @see https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap
 */

import { MetadataRoute } from 'next';

// Base URL configuration - Set this in your environment variables
const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://muslimeen.space';

// ============================================================================
// STATIC PAGE CONFIGURATIONS
// ============================================================================

const STATIC_PAGES = [
  { path: '', priority: 1.0, changeFrequency: 'daily' as const },
  { path: '/about', priority: 0.8, changeFrequency: 'monthly' as const },
  { path: '/islamic-finance', priority: 0.9, changeFrequency: 'weekly' as const },
  { path: '/connections', priority: 0.7, changeFrequency: 'weekly' as const },
  { path: '/login', priority: 0.6, changeFrequency: 'monthly' as const },
];

// Marketplace verticals - Main pillars
const MARKETPLACE_VERTICALS = [
  { path: '/marketplace/earn', priority: 0.9, changeFrequency: 'daily' as const },
  { path: '/marketplace/build', priority: 0.9, changeFrequency: 'daily' as const },
  { path: '/marketplace/live', priority: 0.9, changeFrequency: 'daily' as const },
  { path: '/marketplace/protect', priority: 0.9, changeFrequency: 'daily' as const },
];

// Islamic Finance specific pages
const ISLAMIC_FINANCE_PAGES = [
  { path: '/islamic-finance?tool=zakat', priority: 0.8, changeFrequency: 'monthly' as const },
  { path: '/islamic-finance?tool=sadaqah', priority: 0.8, changeFrequency: 'weekly' as const },
  { path: '/islamic-finance?tool=qard', priority: 0.8, changeFrequency: 'weekly' as const },
  { path: '/islamic-finance?tool=waqf', priority: 0.8, changeFrequency: 'weekly' as const },
];

// Legal and informational pages
const INFO_PAGES = [
  { path: '/privacy', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/terms', priority: 0.5, changeFrequency: 'monthly' as const },
];

// ============================================================================
// DYNAMIC CONTENT FETCHERS
// ============================================================================

/**
 * Fetch public profiles for sitemap
 * These are public profile pages that should be indexed
 */
async function fetchPublicProfiles(): Promise<Array<{ id: string; updatedAt: string }>> {
  try {
    // In production, fetch from your API
    // const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api';
    // const response = await fetch(`${apiUrl}/profiles/public/sitemap`);
    // if (!response.ok) throw new Error('Failed to fetch profiles');
    // return response.json();
    
    // For now, return empty - implement when you have public profile pages
    return [];
  } catch (error) {
    console.error('Error fetching profiles for sitemap:', error);
    return [];
  }
}

/**
 * Fetch marketplace listings for sitemap
 */
async function fetchMarketplaceListings(): Promise<Array<{ id: string; vertical: string; updatedAt: string }>> {
  try {
    // In production, fetch from your API
    // const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api';
    // const response = await fetch(`${apiUrl}/marketplace/sitemap`);
    // if (!response.ok) throw new Error('Failed to fetch listings');
    // return response.json();
    
    // For now, return empty - implement when listings are public
    return [];
  } catch (error) {
    console.error('Error fetching marketplace listings for sitemap:', error);
    return [];
  }
}

// ============================================================================
// SITEMAP GENERATION
// ============================================================================

/**
 * Generate static page entries
 */
function generateStaticEntries(): MetadataRoute.Sitemap {
  const allStatic = [
    ...STATIC_PAGES,
    ...MARKETPLACE_VERTICALS,
    ...ISLAMIC_FINANCE_PAGES,
    ...INFO_PAGES,
  ];
  
  return allStatic.map((page) => ({
    url: `${baseUrl}${page.path}`,
    lastModified: new Date(),
    changeFrequency: page.changeFrequency,
    priority: page.priority,
  }));
}

/**
 * Main sitemap generation function
 * Next.js automatically converts this to /sitemap.xml
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  // Start with static entries
  const staticEntries = generateStaticEntries();
  
  // Initialize dynamic entries array
  let dynamicEntries: MetadataRoute.Sitemap = [];
  
  // Fetch dynamic content (only in production environment)
  if (process.env.NODE_ENV === 'production') {
    try {
      // Public profile pages
      const profiles = await fetchPublicProfiles();
      const profileEntries = profiles.map((profile) => ({
        url: `${baseUrl}/people/${profile.id}`,
        lastModified: new Date(profile.updatedAt),
        changeFrequency: 'weekly' as const,
        priority: 0.6,
      }));
      
      // Marketplace listings
      const listings = await fetchMarketplaceListings();
      const listingEntries = listings.map((listing) => ({
        url: `${baseUrl}/marketplace/${listing.vertical}/${listing.id}`,
        lastModified: new Date(listing.updatedAt),
        changeFrequency: 'daily' as const,
        priority: 0.7,
      }));
      
      dynamicEntries = [...profileEntries, ...listingEntries];
    } catch (error) {
      console.error('Error generating dynamic sitemap entries:', error);
      // Continue with static entries only
    }
  }
  
  return [...staticEntries, ...dynamicEntries];
}

/**
 * Revalidation: Regenerate sitemap every hour
 * This ensures new content is discovered quickly by search engines
 */
export const revalidate = 3600; // 1 hour

/**
 * Route segment config
 * Ensures this route is dynamically rendered to fetch fresh data
 */
export const dynamic = 'force-dynamic';
