#!/usr/bin/env ts-node
/**
 * Generate Stability Report
 * 
 * Creates a comprehensive stability report from monitoring data.
 * 
 * Usage:
 *   npx ts-node scripts/generate-stability-report.ts [environment]
 * 
 * DATE: 2026-03-20
 */

import * as fs from 'fs';
import * as path from 'path';

const colors = {
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
  reset: '\x1b[0m',
};

interface StabilityData {
  environment: string;
  startTime: number;
  samples: Array<{
    timestamp: number;
    backendHealthy: boolean;
    frontendHealthy: boolean;
    backendResponseTime: number;
    frontendResponseTime: number;
    errorDetected: boolean;
  }>;
}

function generateMarkdownReport(data: StabilityData): string {
  const runtime = Date.now() - data.startTime;
  const runtimeHours = runtime / (1000 * 60 * 60);
  
  const totalSamples = data.samples.length;
  const errorCount = data.samples.filter(s => s.errorDetected).length;
  const backendFailures = data.samples.filter(s => !s.backendHealthy).length;
  
  const backendSamples = data.samples.filter(s => s.backendHealthy);
  const avgBackendTime = backendSamples.length > 0
    ? backendSamples.reduce((sum, s) => sum + s.backendResponseTime, 0) / backendSamples.length
    : 0;
  
  const frontendSamples = data.samples.filter(s => s.frontendHealthy);
  const avgFrontendTime = frontendSamples.length > 0
    ? frontendSamples.reduce((sum, s) => sum + s.frontendResponseTime, 0) / frontendSamples.length
    : 0;
  
  const availability = totalSamples > 0
    ? (totalSamples - backendFailures) / totalSamples
    : 1;
  
  const errorRate = totalSamples > 0 ? errorCount / totalSamples : 0;
  
  // Calculate p95 response time
  const sortedTimes = [...backendSamples.map(s => s.backendResponseTime)].sort((a, b) => a - b);
  const p95Index = Math.floor(sortedTimes.length * 0.95);
  const p95Time = sortedTimes[p95Index] || 0;
  
  // Determine status
  const isHealthy = 
    availability >= 0.995 &&
    errorRate < 0.005 &&
    avgBackendTime < 1000;
  
  const report = `# Stability Report

**Environment**: ${data.environment.toUpperCase()}  
**Generated**: ${new Date().toISOString()}  
**Monitoring Period**: ${runtimeHours.toFixed(1)} hours  
**Total Samples**: ${totalSamples}

---

## Executive Summary

**Overall Status**: ${isHealthy ? '✅ STABLE' : '⚠️  ISSUES DETECTED'}

${isHealthy 
  ? 'System has demonstrated stable operation over the monitoring period.' 
  : 'System stability concerns detected. Review metrics below.'}

---

## Key Metrics

| Metric | Value | Target | Status |
|--------|-------|--------|--------|
| **Availability** | ${(availability * 100).toFixed(3)}% | 99.5% | ${availability >= 0.995 ? '✅' : '⚠️'} |
| **Error Rate** | ${(errorRate * 100).toFixed(3)}% | < 0.5% | ${errorRate < 0.005 ? '✅' : '⚠️'} |
| **Avg Response** | ${Math.round(avgBackendTime)}ms | < 1000ms | ${avgBackendTime < 1000 ? '✅' : '⚠️'} |
| **P95 Response** | ${Math.round(p95Time)}ms | < 2000ms | ${p95Time < 2000 ? '✅' : '⚠️'} |
| **Frontend Avg** | ${Math.round(avgFrontendTime)}ms | < 1000ms | ${avgFrontendTime < 1000 ? '✅' : '⚠️'} |

---

## Detailed Statistics

### Availability
- **Uptime**: ${((runtimeHours * availability)).toFixed(2)} hours
- **Downtime Incidents**: ${backendFailures}
- **Longest Downtime**: N/A

### Performance
- **Backend (avg)**: ${Math.round(avgBackendTime)}ms
- **Backend (p95)**: ${Math.round(p95Time)}ms
- **Frontend (avg)**: ${Math.round(avgFrontendTime)}ms
- **Samples Collected**: ${totalSamples}

### Errors
- **Total Errors**: ${errorCount}
- **Error Rate**: ${(errorRate * 100).toFixed(4)}%
- **Errors per Hour**: ${(errorCount / Math.max(runtimeHours, 0.1)).toFixed(2)}

---

## Trends

${generateTrendAnalysis(data.samples)}

---

## Recommendations

${generateRecommendations({ availability, errorRate, avgBackendTime, p95Time })}

---

## Sign-Off

| Role | Status | Notes |
|------|--------|-------|
| Tech Lead | ⬜ Approved | |
| DevOps | ⬜ Approved | |
| On-Call | ⬜ Approved | |

**Date**: _______________

---

*Report generated by long-term stability monitoring system*
`;

  return report;
}

function generateTrendAnalysis(samples: StabilityData['samples']): string {
  if (samples.length < 20) {
    return '> Insufficient data for trend analysis (need 20+ samples)';
  }
  
  const half = Math.floor(samples.length / 2);
  const firstHalf = samples.slice(0, half);
  const secondHalf = samples.slice(half);
  
  // Error trend
  const firstErrors = firstHalf.filter(s => s.errorDetected).length / firstHalf.length;
  const secondErrors = secondHalf.filter(s => s.errorDetected).length / secondHalf.length;
  
  let errorTrend = 'Stable';
  if (secondErrors < firstErrors * 0.8) errorTrend = 'Improving ✅';
  else if (secondErrors > firstErrors * 1.2) errorTrend = 'Degrading ⚠️';
  
  // Response time trend
  const firstTimes = firstHalf.filter(s => s.backendHealthy).map(s => s.backendResponseTime);
  const secondTimes = secondHalf.filter(s => s.backendHealthy).map(s => s.backendResponseTime);
  
  const firstAvg = firstTimes.reduce((a, b) => a + b, 0) / firstTimes.length;
  const secondAvg = secondTimes.reduce((a, b) => a + b, 0) / secondTimes.length;
  
  let timeTrend = 'Stable';
  if (secondAvg < firstAvg * 0.9) timeTrend = 'Improving ✅';
  else if (secondAvg > firstAvg * 1.1) timeTrend = 'Degrading ⚠️';
  
  return `
| Metric | First Half | Second Half | Trend |
|--------|------------|-------------|-------|
| Error Rate | ${(firstErrors * 100).toFixed(2)}% | ${(secondErrors * 100).toFixed(2)}% | ${errorTrend} |
| Avg Response | ${Math.round(firstAvg)}ms | ${Math.round(secondAvg)}ms | ${timeTrend} |
`;
}

function generateRecommendations(metrics: { 
  availability: number; 
  errorRate: number; 
  avgBackendTime: number;
  p95Time: number;
}): string {
  const recs: string[] = [];
  
  if (metrics.availability < 0.99) {
    recs.push('- **CRITICAL**: Availability below 99%. Investigate downtime causes immediately.');
  } else if (metrics.availability < 0.995) {
    recs.push('- **WARNING**: Availability below 99.5%. Review uptime improvements.');
  }
  
  if (metrics.errorRate > 0.01) {
    recs.push('- **CRITICAL**: Error rate exceeds 1%. Review error logs immediately.');
  } else if (metrics.errorRate > 0.005) {
    recs.push('- **WARNING**: Error rate above 0.5%. Monitor closely for patterns.');
  }
  
  if (metrics.avgBackendTime > 1000) {
    recs.push('- **WARNING**: Response time high. Consider performance optimization.');
  }
  
  if (metrics.p95Time > 2000) {
    recs.push('- **WARNING**: P95 response time exceeds 2s. Some users experiencing slow responses.');
  }
  
  if (recs.length === 0) {
    recs.push('- ✅ System performing within expected parameters');
    recs.push('- Continue normal monitoring schedule');
    recs.push('- Document current metrics as new baseline');
  }
  
  return recs.join('\n');
}

// Main
async function main() {
  const environment = process.argv[2] || 'production';
  
  // Find latest report file
  const logsDir = path.join(process.cwd(), 'logs');
  
  if (!fs.existsSync(logsDir)) {
    console.error('No logs directory found. Run monitoring first.');
    process.exit(1);
  }
  
  const files = fs.readdirSync(logsDir)
    .filter(f => f.startsWith(`stability-report-${environment}`) && f.endsWith('.json'))
    .sort()
    .reverse();
  
  if (files.length === 0) {
    console.error(`No stability data found for ${environment}`);
    process.exit(1);
  }
  
  const latestFile = files[0];
  const data: StabilityData = JSON.parse(fs.readFileSync(path.join(logsDir, latestFile), 'utf-8'));
  
  console.log(`\n${colors.cyan}╔═══════════════════════════════════════════════════════════╗${colors.reset}`);
  console.log(`${colors.cyan}║       GENERATING STABILITY REPORT                         ║${colors.reset}`);
  console.log(`${colors.cyan}╚═══════════════════════════════════════════════════════════╝${colors.reset}\n`);
  
  console.log(`Using data: ${latestFile}`);
  console.log(`Samples: ${data.samples.length}`);
  console.log(`Runtime: ${((Date.now() - data.startTime) / (1000 * 60 * 60)).toFixed(1)} hours\n`);
  
  const report = generateMarkdownReport(data);
  
  const outputFile = `STABILITY-REPORT-${environment.toUpperCase()}-${new Date().toISOString().split('T')[0]}.md`;
  fs.writeFileSync(outputFile, report);
  
  console.log(`${colors.green}✅ Report generated: ${outputFile}${colors.reset}\n`);
  
  // Print summary
  const metrics = data.samples;
  const total = metrics.length;
  const errors = metrics.filter(s => s.errorDetected).length;
  const availability = (total - metrics.filter(s => !s.backendHealthy).length) / total;
  
  console.log('Quick Summary:');
  console.log(`  Availability: ${(availability * 100).toFixed(2)}%`);
  console.log(`  Error Rate: ${((errors / total) * 100).toFixed(3)}%`);
  console.log(`  Status: ${availability >= 0.995 && errors / total < 0.005 ? colors.green + 'STABLE' + colors.reset : colors.yellow + 'REVIEW NEEDED' + colors.reset}`);
}

main().catch(console.error);
